package com.ailk.eaap.op2.serviceagent.common;

import java.util.IdentityHashMap;
import java.util.List;
import java.util.Map;
import java.util.Vector;
import org.junit.*;
import static org.junit.Assert.*;

/**
 * The class <code>TuxedoClientTest</code> contains tests for the class <code>{@link TuxedoClient}</code>.
 *
 * @generatedBy CodePro at 15-12-21 下午4:45
 * @author wuwz
 * @version $Revision: 1.0 $
 */
public class TuxedoClientTest {
	/**
	 * Run the void tuxedocall(String,int,String,String,String,String,List<CallParamter>,List<CallParamter>,Map<String,Object>) method test.
	 *
	 * @throws Exception
	 *
	 * @generatedBy CodePro at 15-12-21 下午4:45
	 */
	@Test
	public void testTuxedocall_1()
		throws Exception {
		String address = "";
		int timeout = 1;
		String charset = "";
		String username = "";
		String password = "";
		String sessionname = "";
		List<CallParamter> callParamters = new Vector();
		List<CallParamter> returnParamters = new Vector();
		Map<String, Object> map = new IdentityHashMap();

		TuxedoClient.tuxedocall(address, timeout, charset, username, password, sessionname, callParamters, returnParamters, map);

		// add additional test code here
		// An unexpected exception was thrown in user code while executing this test:
		//    org.springframework.context.NoSuchMessageException: No message found under code 'o2p-serviceagent-core.9999' for locale 'zh_CN'.
		//       at org.springframework.context.support.AbstractMessageSource.getMessage(AbstractMessageSource.java:159)
		//       at com.asiainfo.foundation.util.MessageSourceUtils.getMessage(MessageSourceUtils.java:41)
		//       at com.asiainfo.foundation.exception.BusinessException.getMessage(BusinessException.java:151)
		//       at com.asiainfo.foundation.exception.BusinessException.<init>(BusinessException.java:105)
		//       at com.ailk.eaap.op2.serviceagent.common.TuxedoClient.tuxedocall(TuxedoClient.java:125)
	}

	/**
	 * Run the void tuxedocall(String,int,String,String,String,String,List<CallParamter>,List<CallParamter>,Map<String,Object>) method test.
	 *
	 * @throws Exception
	 *
	 * @generatedBy CodePro at 15-12-21 下午4:45
	 */
	@Test
	public void testTuxedocall_2()
		throws Exception {
		String address = "";
		int timeout = 1;
		String charset = "";
		String username = "";
		String password = "";
		String sessionname = "";
		List<CallParamter> callParamters = new Vector();
		List<CallParamter> returnParamters = new Vector();
		Map<String, Object> map = new IdentityHashMap();

		TuxedoClient.tuxedocall(address, timeout, charset, username, password, sessionname, callParamters, returnParamters, map);

		// add additional test code here
		// An unexpected exception was thrown in user code while executing this test:
		//    org.springframework.context.NoSuchMessageException: No message found under code 'o2p-serviceagent-core.9999' for locale 'zh_CN'.
		//       at org.springframework.context.support.AbstractMessageSource.getMessage(AbstractMessageSource.java:159)
		//       at com.asiainfo.foundation.util.MessageSourceUtils.getMessage(MessageSourceUtils.java:41)
		//       at com.asiainfo.foundation.exception.BusinessException.getMessage(BusinessException.java:151)
		//       at com.asiainfo.foundation.exception.BusinessException.<init>(BusinessException.java:105)
		//       at com.ailk.eaap.op2.serviceagent.common.TuxedoClient.tuxedocall(TuxedoClient.java:125)
	}

	/**
	 * Run the void tuxedocall(String,int,String,String,String,String,List<CallParamter>,List<CallParamter>,Map<String,Object>) method test.
	 *
	 * @throws Exception
	 *
	 * @generatedBy CodePro at 15-12-21 下午4:45
	 */
	@Test
	public void testTuxedocall_3()
		throws Exception {
		String address = "";
		int timeout = 1;
		String charset = "";
		String username = "";
		String password = "";
		String sessionname = "";
		List<CallParamter> callParamters = new Vector();
		List<CallParamter> returnParamters = new Vector();
		Map<String, Object> map = new IdentityHashMap();

		TuxedoClient.tuxedocall(address, timeout, charset, username, password, sessionname, callParamters, returnParamters, map);

		// add additional test code here
		// An unexpected exception was thrown in user code while executing this test:
		//    org.springframework.context.NoSuchMessageException: No message found under code 'o2p-serviceagent-core.9999' for locale 'zh_CN'.
		//       at org.springframework.context.support.AbstractMessageSource.getMessage(AbstractMessageSource.java:159)
		//       at com.asiainfo.foundation.util.MessageSourceUtils.getMessage(MessageSourceUtils.java:41)
		//       at com.asiainfo.foundation.exception.BusinessException.getMessage(BusinessException.java:151)
		//       at com.asiainfo.foundation.exception.BusinessException.<init>(BusinessException.java:105)
		//       at com.ailk.eaap.op2.serviceagent.common.TuxedoClient.tuxedocall(TuxedoClient.java:125)
	}

	/**
	 * Run the void tuxedocall(String,int,String,String,String,String,List<CallParamter>,List<CallParamter>,Map<String,Object>) method test.
	 *
	 * @throws Exception
	 *
	 * @generatedBy CodePro at 15-12-21 下午4:45
	 */
	@Test
	public void testTuxedocall_4()
		throws Exception {
		String address = "";
		int timeout = 1;
		String charset = "";
		String username = "";
		String password = "";
		String sessionname = "";
		List<CallParamter> callParamters = new Vector();
		List<CallParamter> returnParamters = new Vector();
		Map<String, Object> map = new IdentityHashMap();

		TuxedoClient.tuxedocall(address, timeout, charset, username, password, sessionname, callParamters, returnParamters, map);

		// add additional test code here
		// An unexpected exception was thrown in user code while executing this test:
		//    org.springframework.context.NoSuchMessageException: No message found under code 'o2p-serviceagent-core.9999' for locale 'zh_CN'.
		//       at org.springframework.context.support.AbstractMessageSource.getMessage(AbstractMessageSource.java:159)
		//       at com.asiainfo.foundation.util.MessageSourceUtils.getMessage(MessageSourceUtils.java:41)
		//       at com.asiainfo.foundation.exception.BusinessException.getMessage(BusinessException.java:151)
		//       at com.asiainfo.foundation.exception.BusinessException.<init>(BusinessException.java:105)
		//       at com.ailk.eaap.op2.serviceagent.common.TuxedoClient.tuxedocall(TuxedoClient.java:125)
	}

	/**
	 * Run the void tuxedocall(String,int,String,String,String,String,List<CallParamter>,List<CallParamter>,Map<String,Object>) method test.
	 *
	 * @throws Exception
	 *
	 * @generatedBy CodePro at 15-12-21 下午4:45
	 */
	@Test
	public void testTuxedocall_5()
		throws Exception {
		String address = "";
		int timeout = 1;
		String charset = "";
		String username = "";
		String password = "";
		String sessionname = "";
		List<CallParamter> callParamters = new Vector();
		List<CallParamter> returnParamters = new Vector();
		Map<String, Object> map = new IdentityHashMap();

		TuxedoClient.tuxedocall(address, timeout, charset, username, password, sessionname, callParamters, returnParamters, map);

		// add additional test code here
		// An unexpected exception was thrown in user code while executing this test:
		//    org.springframework.context.NoSuchMessageException: No message found under code 'o2p-serviceagent-core.9999' for locale 'zh_CN'.
		//       at org.springframework.context.support.AbstractMessageSource.getMessage(AbstractMessageSource.java:159)
		//       at com.asiainfo.foundation.util.MessageSourceUtils.getMessage(MessageSourceUtils.java:41)
		//       at com.asiainfo.foundation.exception.BusinessException.getMessage(BusinessException.java:151)
		//       at com.asiainfo.foundation.exception.BusinessException.<init>(BusinessException.java:105)
		//       at com.ailk.eaap.op2.serviceagent.common.TuxedoClient.tuxedocall(TuxedoClient.java:125)
	}

	/**
	 * Run the void tuxedocall(String,int,String,String,String,String,List<CallParamter>,List<CallParamter>,Map<String,Object>) method test.
	 *
	 * @throws Exception
	 *
	 * @generatedBy CodePro at 15-12-21 下午4:45
	 */
	@Test
	public void testTuxedocall_6()
		throws Exception {
		String address = "";
		int timeout = 1;
		String charset = "";
		String username = "";
		String password = "";
		String sessionname = "";
		List<CallParamter> callParamters = new Vector();
		List<CallParamter> returnParamters = new Vector();
		Map<String, Object> map = new IdentityHashMap();

		TuxedoClient.tuxedocall(address, timeout, charset, username, password, sessionname, callParamters, returnParamters, map);

		// add additional test code here
		// An unexpected exception was thrown in user code while executing this test:
		//    org.springframework.context.NoSuchMessageException: No message found under code 'o2p-serviceagent-core.9999' for locale 'zh_CN'.
		//       at org.springframework.context.support.AbstractMessageSource.getMessage(AbstractMessageSource.java:159)
		//       at com.asiainfo.foundation.util.MessageSourceUtils.getMessage(MessageSourceUtils.java:41)
		//       at com.asiainfo.foundation.exception.BusinessException.getMessage(BusinessException.java:151)
		//       at com.asiainfo.foundation.exception.BusinessException.<init>(BusinessException.java:105)
		//       at com.ailk.eaap.op2.serviceagent.common.TuxedoClient.tuxedocall(TuxedoClient.java:125)
	}

	/**
	 * Run the void tuxedocall(String,int,String,String,String,String,List<CallParamter>,List<CallParamter>,Map<String,Object>) method test.
	 *
	 * @throws Exception
	 *
	 * @generatedBy CodePro at 15-12-21 下午4:45
	 */
	@Test
	public void testTuxedocall_7()
		throws Exception {
		String address = "";
		int timeout = 1;
		String charset = "";
		String username = "";
		String password = "";
		String sessionname = "";
		List<CallParamter> callParamters = new Vector();
		List<CallParamter> returnParamters = new Vector();
		Map<String, Object> map = new IdentityHashMap();

		TuxedoClient.tuxedocall(address, timeout, charset, username, password, sessionname, callParamters, returnParamters, map);

		// add additional test code here
		// An unexpected exception was thrown in user code while executing this test:
		//    org.springframework.context.NoSuchMessageException: No message found under code 'o2p-serviceagent-core.9999' for locale 'zh_CN'.
		//       at org.springframework.context.support.AbstractMessageSource.getMessage(AbstractMessageSource.java:159)
		//       at com.asiainfo.foundation.util.MessageSourceUtils.getMessage(MessageSourceUtils.java:41)
		//       at com.asiainfo.foundation.exception.BusinessException.getMessage(BusinessException.java:151)
		//       at com.asiainfo.foundation.exception.BusinessException.<init>(BusinessException.java:105)
		//       at com.ailk.eaap.op2.serviceagent.common.TuxedoClient.tuxedocall(TuxedoClient.java:125)
	}

	/**
	 * Run the void tuxedocall(String,int,String,String,String,String,List<CallParamter>,List<CallParamter>,Map<String,Object>) method test.
	 *
	 * @throws Exception
	 *
	 * @generatedBy CodePro at 15-12-21 下午4:45
	 */
	@Test
	public void testTuxedocall_8()
		throws Exception {
		String address = "";
		int timeout = 1;
		String charset = "";
		String username = "";
		String password = "";
		String sessionname = "";
		List<CallParamter> callParamters = new Vector();
		List<CallParamter> returnParamters = new Vector();
		Map<String, Object> map = new IdentityHashMap();

		TuxedoClient.tuxedocall(address, timeout, charset, username, password, sessionname, callParamters, returnParamters, map);

		// add additional test code here
		// An unexpected exception was thrown in user code while executing this test:
		//    org.springframework.context.NoSuchMessageException: No message found under code 'o2p-serviceagent-core.9999' for locale 'zh_CN'.
		//       at org.springframework.context.support.AbstractMessageSource.getMessage(AbstractMessageSource.java:159)
		//       at com.asiainfo.foundation.util.MessageSourceUtils.getMessage(MessageSourceUtils.java:41)
		//       at com.asiainfo.foundation.exception.BusinessException.getMessage(BusinessException.java:151)
		//       at com.asiainfo.foundation.exception.BusinessException.<init>(BusinessException.java:105)
		//       at com.ailk.eaap.op2.serviceagent.common.TuxedoClient.tuxedocall(TuxedoClient.java:125)
	}

	/**
	 * Run the void tuxedocall(String,int,String,String,String,String,List<CallParamter>,List<CallParamter>,Map<String,Object>) method test.
	 *
	 * @throws Exception
	 *
	 * @generatedBy CodePro at 15-12-21 下午4:45
	 */
	@Test
	public void testTuxedocall_9()
		throws Exception {
		String address = "";
		int timeout = 1;
		String charset = "";
		String username = "";
		String password = "";
		String sessionname = "";
		List<CallParamter> callParamters = new Vector();
		List<CallParamter> returnParamters = null;
		Map<String, Object> map = new IdentityHashMap();

		TuxedoClient.tuxedocall(address, timeout, charset, username, password, sessionname, callParamters, returnParamters, map);

		// add additional test code here
		// An unexpected exception was thrown in user code while executing this test:
		//    org.springframework.context.NoSuchMessageException: No message found under code 'o2p-serviceagent-core.9999' for locale 'zh_CN'.
		//       at org.springframework.context.support.AbstractMessageSource.getMessage(AbstractMessageSource.java:159)
		//       at com.asiainfo.foundation.util.MessageSourceUtils.getMessage(MessageSourceUtils.java:41)
		//       at com.asiainfo.foundation.exception.BusinessException.getMessage(BusinessException.java:151)
		//       at com.asiainfo.foundation.exception.BusinessException.<init>(BusinessException.java:105)
		//       at com.ailk.eaap.op2.serviceagent.common.TuxedoClient.tuxedocall(TuxedoClient.java:125)
	}

	/**
	 * Run the void tuxedocall(String,int,String,String,String,String,List<CallParamter>,List<CallParamter>,Map<String,Object>) method test.
	 *
	 * @throws Exception
	 *
	 * @generatedBy CodePro at 15-12-21 下午4:45
	 */
	@Test
	public void testTuxedocall_10()
		throws Exception {
		String address = "";
		int timeout = 1;
		String charset = "";
		String username = "";
		String password = "";
		String sessionname = "";
		List<CallParamter> callParamters = new Vector();
		List<CallParamter> returnParamters = new Vector();
		Map<String, Object> map = new IdentityHashMap();

		TuxedoClient.tuxedocall(address, timeout, charset, username, password, sessionname, callParamters, returnParamters, map);

		// add additional test code here
		// An unexpected exception was thrown in user code while executing this test:
		//    org.springframework.context.NoSuchMessageException: No message found under code 'o2p-serviceagent-core.9999' for locale 'zh_CN'.
		//       at org.springframework.context.support.AbstractMessageSource.getMessage(AbstractMessageSource.java:159)
		//       at com.asiainfo.foundation.util.MessageSourceUtils.getMessage(MessageSourceUtils.java:41)
		//       at com.asiainfo.foundation.exception.BusinessException.getMessage(BusinessException.java:151)
		//       at com.asiainfo.foundation.exception.BusinessException.<init>(BusinessException.java:105)
		//       at com.ailk.eaap.op2.serviceagent.common.TuxedoClient.tuxedocall(TuxedoClient.java:125)
	}

	/**
	 * Run the void tuxedocall(String,int,String,String,String,String,List<CallParamter>,List<CallParamter>,Map<String,Object>) method test.
	 *
	 * @throws Exception
	 *
	 * @generatedBy CodePro at 15-12-21 下午4:45
	 */
	@Test
	public void testTuxedocall_11()
		throws Exception {
		String address = "";
		int timeout = 1;
		String charset = "";
		String username = "";
		String password = "";
		String sessionname = "";
		List<CallParamter> callParamters = null;
		List<CallParamter> returnParamters = new Vector();
		Map<String, Object> map = new IdentityHashMap();

		TuxedoClient.tuxedocall(address, timeout, charset, username, password, sessionname, callParamters, returnParamters, map);

		// add additional test code here
		// An unexpected exception was thrown in user code while executing this test:
		//    org.springframework.context.NoSuchMessageException: No message found under code 'o2p-serviceagent-core.9999' for locale 'zh_CN'.
		//       at org.springframework.context.support.AbstractMessageSource.getMessage(AbstractMessageSource.java:159)
		//       at com.asiainfo.foundation.util.MessageSourceUtils.getMessage(MessageSourceUtils.java:41)
		//       at com.asiainfo.foundation.exception.BusinessException.getMessage(BusinessException.java:151)
		//       at com.asiainfo.foundation.exception.BusinessException.<init>(BusinessException.java:105)
		//       at com.ailk.eaap.op2.serviceagent.common.TuxedoClient.tuxedocall(TuxedoClient.java:125)
	}

	/**
	 * Run the void tuxedocall(String,int,String,String,String,String,List<CallParamter>,List<CallParamter>,Map<String,Object>) method test.
	 *
	 * @throws Exception
	 *
	 * @generatedBy CodePro at 15-12-21 下午4:45
	 */
	@Test
	public void testTuxedocall_12()
		throws Exception {
		String address = "";
		int timeout = 1;
		String charset = "";
		String username = "";
		String password = "";
		String sessionname = "";
		List<CallParamter> callParamters = new Vector();
		List<CallParamter> returnParamters = new Vector();
		Map<String, Object> map = new IdentityHashMap();

		TuxedoClient.tuxedocall(address, timeout, charset, username, password, sessionname, callParamters, returnParamters, map);

		// add additional test code here
		// An unexpected exception was thrown in user code while executing this test:
		//    org.springframework.context.NoSuchMessageException: No message found under code 'o2p-serviceagent-core.9999' for locale 'zh_CN'.
		//       at org.springframework.context.support.AbstractMessageSource.getMessage(AbstractMessageSource.java:159)
		//       at com.asiainfo.foundation.util.MessageSourceUtils.getMessage(MessageSourceUtils.java:41)
		//       at com.asiainfo.foundation.exception.BusinessException.getMessage(BusinessException.java:151)
		//       at com.asiainfo.foundation.exception.BusinessException.<init>(BusinessException.java:105)
		//       at com.ailk.eaap.op2.serviceagent.common.TuxedoClient.tuxedocall(TuxedoClient.java:125)
	}

	/**
	 * Perform pre-test initialization.
	 *
	 * @throws Exception
	 *         if the initialization fails for some reason
	 *
	 * @generatedBy CodePro at 15-12-21 下午4:45
	 */
	@Before
	public void setUp()
		throws Exception {
		// add additional set up code here
	}

	/**
	 * Perform post-test clean-up.
	 *
	 * @throws Exception
	 *         if the clean-up fails for some reason
	 *
	 * @generatedBy CodePro at 15-12-21 下午4:45
	 */
	@After
	public void tearDown()
		throws Exception {
		// Add additional tear down code here
	}

	/**
	 * Launch the test.
	 *
	 * @param args the command line arguments
	 *
	 * @generatedBy CodePro at 15-12-21 下午4:45
	 */
	public static void main(String[] args) {
		new org.junit.runner.JUnitCore().run(TuxedoClientTest.class);
	}
}